language: python
python:
- '2.7'
sudo: false
env:
- DJANGO_VERSION=">=1.8,<1.9"
- DJANGO_VERSION=">=1.9,<1.10"
- DJANGO_VERSION=">=1.10,<1.11"
install:
- pip install "Django$DJANGO_VERSION"
script:
- make test
notifications:
  slack: tlt:KyqrXDeFkXKb72AsDYTwWkNp
deploy:
  provider: pypi
  user: tlt_opensource
  distributions: sdist bdist_wheel
  password:
    secure: "FpeaTjuWpwgWUJ/FagTc7FJtIBCHRufOnDHsI8s8W8gu3EDrcIqCohbAOkEBUM2WCI2wzmhNHYciRXQQQnLdGyJvbOf9XKG2yoo4QDgEQ8en+i0dgoqUag5deXfH6kxjBzpaBAN9vX9pervEJa51pR3ci1qnMU51UdsBWuY2vUC3ez5+F8BsMnRq95mVypSnJLz8holg4hoC7x6utsxtk7lwJCnlheNOGW+aodzldaRsrAPCUq+NpsGIxjKF0JV1XvhNsiGODHjDrWVWsZo/gBPjMu18b/q4O/9AMBl0uMv3unVXroCyber9T8UkHnQepYQlFiVZAj4lbGUEFKr+gZH3EyntfB23XWMYA/eQ+6YM4d2rjNY+W0EQqMkhJnkSlqf31qqhAPP2XN8rIjRiFd1dFCeS3R971YpGnzS4hxB+G2yjgXfUY/JoFG22SNACSyLvzS90txiBf/MIWVnTV+jDSOrfUBEp/AQ0NNAAvUwA26AlHxeBSqaZEPMwfdOP9OSFbBx8z84yUxFfkfxxsLP37ow2yW38CWYQEtV9jKIpvj0D6KiIpMJgCcE7TTIFaVkbbsVo9pGPWwcSiMxC6RA7KXHPuOTGulDFPexwqaVq3Fx3lXoFFcevB02RkfT2NwiEMR+2Zxilry/0yj3l8ngZIqm6JKaI2EnVvgGPYU4="
  on:
    tags: true
    branch: master
    condition: $DJANGO_VERSION = ">=1.10,<1.11"
